apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: kafka-producer:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080